project:
  type: book
  output-dir: docs

book:
  sidebar:
    tools:
      - icon: github
        href: https://github.com/arbones/TFM
  title: Master of Science in Omics Data Analysis
  chapters:
    - index.qmd
    - intro.qmd
    - part: Supplementary Material
      chapters: 
        - wat&msld.qmd
        - rnaseq.qmd
        - wes.qmd
        - eqtl.qmd
        - biblio.qmd
bibliography: references.bib
csl: begell-house-apa.csl

format:
  html:
    theme: cosmo

